name: simple_live_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  simple_live_core:
    path: ../simple_live_core
  # 图标
  cupertino_icons: ^1.0.2
  remixicon: ^1.0.0 #Remix图标

  # 框架、工具
  get: 4.6.5 #状态管理、路由管理、国际化
  dio: 4.0.6 #网络请求
  hive: 2.2.3 #持久化存储
  hive_flutter: 1.1.0 #持久化存储
  logger: 1.1.0 #日志
  intl: 0.18.0 #国际化

  #Widget
  flutter_staggered_grid_view: 0.6.2 #瀑布流/GridView
  flutter_easyrefresh: 2.2.2 #下拉刷新、上拉加载
  extended_image: 6.3.1 #拓展Image,支持缓存
  flutter_smart_dialog: 4.6.1+5 #各种弹窗 Toast/Dialog/Popup
  sticky_headers: ^0.3.0+2 #吸顶
  lottie: ^1.4.3 #lottie动画
  ns_danmaku: #弹幕
    git: 
        url: https://github.com/xiaoyaocz/flutter_ns_danmaku.git
        ref: master

  #系统交互
  package_info_plus: 3.0.1 #包信息
  url_launcher: 6.1.6 #打开链接
  share_plus: 6.0.1 #分享
  path_provider: 2.0.11 #常用路径
  cross_file: ^0.3.3+2 #跨平台文件
  permission_handler: ^10.0.0 #权限处理
  image_gallery_saver: ^1.7.1 #图片保存到相册
  flutter_vlc_player: ^7.2.0 #视频播放
  perfect_volume_control: ^1.0.5 #音量控制
  screen_brightness: ^0.2.2 #亮度控制
  auto_orientation: ^2.2.1 #屏幕方向
  wakelock: ^0.6.2 #屏幕常亮
  

  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    
dependency_overrides:
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/statement.txt
    - assets/sponsor/
    - assets/images/
    - assets/icons/
    - assets/lotties/

