name: simple_live_core
version: 1.0.0
description: "聚合直播核心库"
repository: https://github.com/xiaoyaocz/simple_live_client
publish_to: "none"
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  dio: 4.0.6
  logger: ^1.1.0
  web_socket_channel: ^2.3.0
  html_unescape: ^2.0.0
  crypto: ^3.0.2
  dart_tars_protocol:
    git: https://github.com/xiaoyaocz/dart_tars_protocol.git

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0

